
#include <stdint.h>

#include <utilities/include/graphics.h>




static const uint16_t image_data_wifi[320] = {
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, 
    BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, 
    BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, 
    BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_BOT, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP, BACKGROUND_TOP
};

